install: true

language: java

jdk:
  - oraclejdk8

services:
  - mongodb

env:
  - PLAY_VERSION=2.11.6
  - AWS_ACCESS_KEY_ID=xxxx
  - AWS_SECRET_ACCESS_KEY=xxxx

script:
-  ./activator compile
#-  ./activator test

notifications:
email: false